# Generated by Django 6.0 on 2025-12-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('worlds', '0002_world_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worlds.world'),
        ),
    ]
