# Generated by Django 6.0 on 2025-12-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, upload_to='')),
                ('coordinates', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
