# Generated by Django 6.0 on 2025-12-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='x_coordinate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinate',
            name='y_coordinate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinate',
            name='z_coordinate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
