# Generated by Django 6.0 on 2025-12-06 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0003_remove_coordinate_coordinates_and_more'),
        ('projects', '0002_project_world'),
        ('worlds', '0002_world_game_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinates', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinates', to='worlds.world'),
        ),
    ]
