# Generated by Django 6.0 on 2025-12-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.CharField(max_length=16)),
                ('edition', models.CharField(choices=[('Java', 'Java'), ('Bedrock', 'Bedrock')], default='Java', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
