# Generated by Django 6.0 on 2025-12-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='game_mode',
            field=models.CharField(choices=[('Survival', 'Survival'), ('Creative', 'Creative'), ('Hardcore', 'Hardcore')], default='Survival', max_length=32),
        ),
    ]
