# Generated by Django 6.0 on 2025-12-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0003_alter_world_owner_alter_world_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
